### ISSUE TITLE
Error - Please help

### ISSUE THREAD

**Issue by vvaz-developer** [ShekharTarare/CSV-Reader-using-ASP.NET-Core#1]
I followed your instructions; however, when I ran the application and clicked on the button "Upload", it directed me to "https://localhost:7037/Home/Upload" and it gave me the following error message:

System.InvalidOperationException: The view 'Upload' was not found. The following locations were searched:
/Views/Home/Upload.cshtml
/Views/Shared/Upload.cshtml
/Pages/Shared/Upload.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

**Comment by ShekharTarare** [comment]
Hi, could you please show your startup and controller code. I am suspecting it could be routing issue. [Here](https://stackoverflow.com/questions/75808380/invalidoperationexception-the-view-index-was-not-found-the-following-locatio) are some other ways to fix it.

**Comment by vvaz-developer** [comment]
Shekhar Tarare,

Please accept my apologies! It was my fault. The root cause was the .csv file that I got uploaded. The names on the columns on the .csv file had spaces and my model class did not. It was causing issues when attempting to bind the data.

For example:

     _public class User
    {
        public string JobTitle { get; set; }
        public string JobNumber { get; set; }
        public string PayPlan { get; set; }
        public string Organization { get; set; }
        public string JobState { get; set; }
        public DateTime CloseDate { get; set; }
        public string JobStatus { get; set; }
        public string ApplicationStatus { get; set; }
        public bool Archived { get; set; }
    }_

while my .csv columns were:

**Job Title,Job Number,Pay Plan,Location,Organization,Job State,Close Date,Job Status,Application Status,Archived**

Please disregard my error since it is no longer an issue. You can go ahead and delete this thread.

Thank you so much for your quick response.

Best regards,
Vince

**Comment by ShekharTarare** [comment]
You’re welcome! 😊 I’m always happy to help.
